KRA_CLOSED_STATUS = "Closed"
KRA_REJECTED_STATUS = "Rejected"
KRA_LOCKED_STATUS = "Submitted"
KRA_OPEN_STATUS = "Open"
KRA_STATUSES = (
    (KRA_CLOSED_STATUS, KRA_CLOSED_STATUS),
    (KRA_REJECTED_STATUS, KRA_REJECTED_STATUS),
    (KRA_LOCKED_STATUS, KRA_LOCKED_STATUS),
    (KRA_OPEN_STATUS, KRA_OPEN_STATUS),
)
KRA_BUCKET_OPEN_STATUS = "Open"
KRA_BUCKET_CLOSED_STATUS = "Closed"
KRA_BUCKET_STATUSES = (
    (KRA_BUCKET_OPEN_STATUS, KRA_BUCKET_OPEN_STATUS),
    (KRA_BUCKET_CLOSED_STATUS, KRA_BUCKET_CLOSED_STATUS)
)
